sonar.organization=cheshire-12

# Уникальный ключ проекта
sonar.projectKey=Cheshire-12_python-project-83
sonar.projectName=Page Analyzer

sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=page_analyzer
sonar.language=py
sonar.python.version=3.14
sonar.exclusions=**/__tests__/**, **/.venv/**, **/node_modules/**